# Generated by Django 4.1.7 on 2023-03-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_rename_pub_date_assignment_deadline_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='deadline_date',
            new_name='pub_date',
        ),
    ]
